---

# ansible-galaxy role install -r requirements.yml
roles:

  - name: eessi.cvmfs
    src: https://github.com/EESSI/ansible-cvmfs
    version: 34b6e07

  - name: geerlingguy.repo-epel
    version: 3.1.1

collections:

  - name: community.general
    version: '>=8.6.1'

