FROM docker.io/ppc64le/centos:7

RUN yum install -y sudo vim openssh-clients cmake wget make unzip patch valgrind bzip2

RUN yum install -y gcc gcc-c++ sqlite-devel python-devel libcap-devel libuuid-devel attr \
 && yum install -y fuse-devel fuse3-devel zlib-devel openssl-devel

# build CernVM-FS from source (no aarch64 Debian packages available)
RUN  wget https://github.com/cvmfs/cvmfs/archive/cvmfs-2.7.5.tar.gz && \
  tar xfz cvmfs-2.7.5.tar.gz && \
  cd cvmfs*2.7.5/ && \
  mkdir build && \
  cd build && \
  cmake .. -DBUILD_SERVER=no -DBUILD_SERVER_DEBUG=no -DDBUILD_SHRINKWRAP=no && \
  make -j $(nproc) && \
  sudo make install && \
  cd / && \
  rm -r cvmfs*2.7.5*

RUN yum install -y https://github.com/EESSI/filesystem-layer/releases/download/v0.2.3/cvmfs-config-eessi-0.2.3-1.noarch.rpm

RUN echo 'CVMFS_QUOTA_LIMIT=10000' > /etc/cvmfs/default.local \
  && echo 'CVMFS_HTTP_PROXY="DIRECT"' >> /etc/cvmfs/default.local

RUN mkdir -p /cvmfs/{cvmfs-config.eessi-hpc.org,pilot.eessi-hpc.org}

RUN useradd -ms /bin/bash eessi
