ARG cvmfsversion=2.13.0
ARG awscliversion=1.40.35
ARG fuseoverlayfsversion=1.15
ARG bwrapversion=0.11.0

FROM debian:12.11 AS prepare-deb
ARG cvmfsversion
COPY ./containers/build-or-download-cvmfs-debs.sh /build-or-download-cvmfs-debs.sh
RUN sh /build-or-download-cvmfs-debs.sh ${cvmfsversion}


FROM debian:12.11
ARG cvmfsversion
ARG awscliversion
ARG fuseoverlayfsversion
ARG bwrapversion

COPY --from=prepare-deb /root/deb /root/deb

RUN apt-get update
RUN apt-get install -y sudo vim openssh-client gawk autofs curl attr uuid fuse3 libfuse2 psmisc gdb uuid-dev lsof strace
# python3 and jq are required for eessi-upload-to-staging script (next to awscli)
RUN apt-get install -y python3-pip jq
RUN dpkg -i /root/deb/cvmfs_${cvmfsversion}~1+debian12_$(dpkg --print-architecture).deb \
            /root/deb/cvmfs-fuse3_${cvmfsversion}~1+debian12_$(dpkg --print-architecture).deb \
            /root/deb/cvmfs-libs_${cvmfsversion}~1+debian12_$(dpkg --print-architecture).deb \
            /root/deb/cvmfs-config-default_latest_all.deb \
            /root/deb/cvmfs-config-eessi_latest_all.deb

# build and install patched version of fuse-overlayfs,
# see also https://github.com/EESSI/software-layer/issues/556
# and https://github.com/containers/fuse-overlayfs/issues/428
RUN apt-get install -y autoconf automake pkg-config libfuse3-dev \
  && curl -OL https://github.com/containers/fuse-overlayfs/archive/refs/tags/v${fuseoverlayfsversion}.tar.gz \
  && tar xfvz v${fuseoverlayfsversion}.tar.gz \
  && cd fuse-overlayfs-${fuseoverlayfsversion} \
  && cp main.c main.c.orig \
  && sed -i 's/find_mapping (st->st_\([ug]id\)/find_mapping (get\1()/g' main.c \
  && sed -i 's/if (st.st_uid.*/if (0)/g' main.c \
  && diff -u main.c.orig main.c || true \
  && sh autogen.sh \
  && LIBS="-ldl" LDFLAGS="-static" ./configure --prefix /usr \
  && make install \
  && command -v fuse-overlayfs \
  && fuse-overlayfs --version \
  && fuse-overlayfs --help \
  && apt-get remove -y autoconf automake pkg-config libfuse3-dev

RUN echo 'CVMFS_QUOTA_LIMIT=10000' > /etc/cvmfs/default.local \
  && echo 'CVMFS_CLIENT_PROFILE="single"' >> /etc/cvmfs/default.local \
  && echo 'CVMFS_HIDE_MAGIC_XATTRS=yes' >> /etc/cvmfs/default.local

RUN mkdir -p /cvmfs/software.eessi.io

RUN useradd -ms /bin/bash eessi

# stick to awscli v1.x, 2.x is not available through PyPI (see https://github.com/aws/aws-cli/issues/4947)
RUN pip3 install --break-system-packages archspec awscli==${awscliversion}
