FROM docker.io/ppc64le/centos:7
ARG cvmfsversion=2.8.0
ARG cvmfsconfig=https://github.com/EESSI/filesystem-layer/releases/download/latest/cvmfs-config-eessi-latest.noarch.rpm

RUN yum install -y sudo vim openssh-clients cmake wget make unzip patch valgrind bzip2

RUN yum install -y gcc gcc-c++ sqlite-devel python-devel libcap-devel libuuid-devel attr \
 && yum install -y fuse-devel fuse3-devel zlib-devel openssl-devel

# build CernVM-FS from source (no aarch64 Debian packages available)
RUN  wget https://github.com/cvmfs/cvmfs/archive/cvmfs-${cvmfsversion}.tar.gz && \
  tar xfz cvmfs-${cvmfsversion}.tar.gz && \
  cd cvmfs*${cvmfsversion}/ && \
  mkdir build && \
  cd build && \
  cmake .. -DBUILD_SERVER=no -DBUILD_SERVER_DEBUG=no -DDBUILD_SHRINKWRAP=no && \
  make -j $(nproc) && \
  sudo make install && \
  cd / && \
  rm -r cvmfs*${cvmfsversion}*

RUN yum install -y ${cvmfsconfig}

RUN yum remove -y fuse && yum install -y fuse3

RUN echo 'CVMFS_QUOTA_LIMIT=10000' > /etc/cvmfs/default.local \
  && echo 'CVMFS_CLIENT_PROFILE="single"' >> /etc/cvmfs/default.local

RUN mkdir -p /cvmfs/{cvmfs-config.eessi-hpc.org,pilot.eessi-hpc.org}

RUN useradd -ms /bin/bash eessi
