ARG cvmfsversion=2.8.1
ARG fuseoverlayfsversion=0.4.1

FROM debian:10.6 AS prepare-deb
ARG cvmfsversion
COPY ./containers/build-or-download-cvmfs-debs.sh /build-or-download-cvmfs-debs.sh
RUN sh /build-or-download-cvmfs-debs.sh ${cvmfsversion}


FROM debian:10.6
ARG cvmfsversion

COPY --from=prepare-deb /root/deb /root/deb

RUN apt-get update
RUN apt-get install -y sudo vim openssh-client gawk autofs curl attr uuid fuse3 libfuse2 psmisc gdb uuid-dev unzip
RUN dpkg -i /root/deb/cvmfs_${cvmfsversion}~1+debian10_$(dpkg --print-architecture).deb \
            /root/deb/cvmfs-fuse3_${cvmfsversion}~1+debian10_$(dpkg --print-architecture).deb \
            /root/deb/cvmfs-config-default_latest_all.deb \
            /root/deb/cvmfs-config-eessi_latest_all.deb

RUN echo 'CVMFS_QUOTA_LIMIT=10000' > /etc/cvmfs/default.local \
  && echo 'CVMFS_CLIENT_PROFILE="single"' >> /etc/cvmfs/default.local

RUN mkdir -p /cvmfs/pilot.eessi-hpc.org

RUN useradd -ms /bin/bash eessi

# see https://docs.aws.amazon.com/cli/latest/userguide/install-cliv2-linux.html#cliv2-linux-install
RUN curl https://awscli.amazonaws.com/awscli-exe-linux-$(uname -m)-2.2.35.zip -o awscliv2.zip \
  && unzip awscliv2.zip \
  && ./aws/install \
  && rm -r aws

RUN curl -OL https://raw.githubusercontent.com/EESSI/infrastructure/main/eessi-upload-to-staging \
  && mv eessi-upload-to-staging /usr/bin \
  && chmod a+x /usr/bin/eessi-upload-to-staging
