ARG cvmfsversion=2.8.1
ARG fuseoverlayfsversion=0.4.1

FROM centos:7 AS prepare-rpm
ARG cvmfsversion
COPY ./containers/build-or-download-cvmfs-rpms.sh /build-or-download-cvmfs-rpms.sh
RUN sh /build-or-download-cvmfs-rpms.sh ${cvmfsversion}


FROM centos:7 AS build-fuse-overlayfs
ARG fuseoverlayfsversion
RUN yum install -y wget fuse3-devel autoconf automake gcc make tar
RUN wget https://github.com/containers/fuse-overlayfs/archive/refs/tags/v${fuseoverlayfsversion}.tar.gz \
  && tar xzf v${fuseoverlayfsversion}.tar.gz \
  && cd fuse-overlayfs-${fuseoverlayfsversion} \
  && ./autogen.sh && ./configure && make && make install


FROM centos:7
ARG cvmfsversion

COPY --from=prepare-rpm /root/rpmbuild/RPMS /root/rpmbuild/RPMS
COPY --from=build-fuse-overlayfs /usr/local/bin/fuse-overlayfs /usr/local/bin/fuse-overlayfs

RUN yum install -y sudo vim openssh-clients
RUN yum install -y /root/rpmbuild/RPMS/$(uname -m)/cvmfs-${cvmfsversion}-1.el7.$(uname -m).rpm \
                   /root/rpmbuild/RPMS/$(uname -m)/cvmfs-fuse3-${cvmfsversion}-1.el7.$(uname -m).rpm \
                   http://ecsft.cern.ch/dist/cvmfs/cvmfs-config/cvmfs-config-default-latest.noarch.rpm
RUN yum install -y https://github.com/EESSI/filesystem-layer/releases/download/latest/cvmfs-config-eessi-latest.noarch.rpm

RUN echo 'CVMFS_QUOTA_LIMIT=10000' > /etc/cvmfs/default.local \
  && echo 'CVMFS_HTTP_PROXY="DIRECT"' >> /etc/cvmfs/default.local

RUN mkdir -p /cvmfs/pilot.eessi-hpc.org

RUN useradd -ms /bin/bash eessi
