FROM docker.io/library/centos:7.8.2003

COPY cvmfs-config-eessi-0.1-1.noarch.rpm /root/cvmfs-config-eessi-0.1-1.noarch.rpm

RUN yum install -y http://cvmrepo.web.cern.ch/cvmrepo/yum/cvmfs-release-latest.noarch.rpm \
 && yum install -y cvmfs cvmfs-config-default cvmfs-fuse3 sudo vim \
 && yum install -y /root/cvmfs-config-eessi-0.1-1.noarch.rpm

RUN echo 'CVMFS_QUOTA_LIMIT=10000' > /etc/cvmfs/default.local \
  && echo 'CVMFS_HTTP_PROXY="DIRECT"' >> /etc/cvmfs/default.local

RUN mkdir -p /cvmfs/{cvmfs-config.eessi-hpc.org,pilot.eessi-hpc.org}

RUN useradd -ms /bin/bash eessi
