# Specifications of files and symlinks for the pilot.eessi-hpc.org CVMFS repository.
# Paths for files and symlinks should be relative to the root of the repository.
---
files: # noqa: var-naming[no-role-prefix]
  - name: .cvmfsdirtab
    dest: ''
    mode: '644'

symlinks:  # noqa: var-naming[no-role-prefix]
  latest: versions/2021.12
  host_injections: '$(EESSI_HOST_INJECTIONS:-/opt/eessi)'
