# Specifications of files and symlinks for the riscv.eessi.io CVMFS repository.
# Paths for files and symlinks should be relative to the root of the repository.
---
files: # noqa: var-naming[no-role-prefix]
  - name: .cvmfsdirtab
    dest: ''
    mode: '644'

  - name: README.riscv
    dest: 'README.eessi'
    mode: '644'

symlinks: # noqa: var-naming[no-role-prefix]
  host_injections: '$(EESSI_HOST_INJECTIONS:-/opt/eessi)'
