# Specifications of files and symlinks for the software.eessi.io CVMFS repository.
# Paths for files and symlinks should be relative to the root of the repository.
---
directories: # noqa: var-naming[no-role-prefix]
  - name: defaults
    mode: '755'

  - name: init/modules/EESSI
    mode: '755'

files: # noqa: var-naming[no-role-prefix]
  - name: .cvmfsdirtab
    dest: ''
    mode: '644'

  - name: README.eessi
    dest: ''
    mode: '644'

  - name: EESSI-modulerc
    dest: 'init/modules/EESSI/.modulerc.lua'
    mode: '644'

symlinks: # noqa: var-naming[no-role-prefix]
  defaults/nvidia: '$(EESSI_NVIDIA_OVERRIDE_DEFAULT:-/dev/null)'
  host_injections: '$(EESSI_HOST_INJECTIONS:-/opt/eessi)'
  init/modules/EESSI/2023.06.lua: /cvmfs/software.eessi.io/versions/2023.06/init/modules/EESSI/2023.06.lua
  init/modules/EESSI/2025.06.lua: /cvmfs/software.eessi.io/versions/2025.06/init/modules/EESSI/2025.06.lua
  versions/2025.06/compat/linux/aarch64/lib/nvidia: '$(EESSI_202506_NVIDIA_OVERRIDE:-/cvmfs/software.eessi.io/defaults/nvidia)'
  versions/2025.06/compat/linux/riscv64/lib/nvidia: '$(EESSI_202506_NVIDIA_OVERRIDE:-/cvmfs/software.eessi.io/defaults/nvidia)'
  versions/2025.06/compat/linux/x86_64/lib/nvidia: '$(EESSI_202506_NVIDIA_OVERRIDE:-/cvmfs/software.eessi.io/defaults/nvidia)'
