# Create specified files and symlinks in the CVMFS repository {{ cvmfs_repo }}.
---

- name: "Include the vars file for {{ cvmfs_repo }}"
  ansible.builtin.include_vars: "{{ cvmfs_repo }}.yml"

- name: Start transaction
  ansible.builtin.command:
    cmd: "cvmfs_server transaction {{ cvmfs_repo }}"
    creates: "/var/spool/cvmfs/{{ cvmfs_repo }}/in_transaction.lock"
  when: create_cvmfs_content_structure_start_transaction

- name: Apply changes to CVMFS repository, if there are any
  block:
    - name: "Create directories"
      ansible.builtin.file:
        path: "/cvmfs/{{ cvmfs_repo }}/{{ item.name }}"
        state: directory
        mode: "{{ item.mode }}"
      with_items: "{{ directories }}"
      register: create_cvmfs_content_structure_create_directories

    - name: "Create symlinks"
      ansible.builtin.file:
        path: "/cvmfs/{{ cvmfs_repo }}/{{ item }}"
        src: "{{ symlinks[item] }}"
        state: link
        force: true
      with_items: "{{ symlinks }}"
      register: create_cvmfs_content_structure_create_symlinks

    - name: "Copy files"
      ansible.builtin.copy:
        src: "{{ item.name }}"
        dest: "/cvmfs/{{ cvmfs_repo }}/{{ item.dest }}"
        mode: "{{ item.mode }}"
      with_items: "{{ files }}"
      register: create_cvmfs_content_structure_create_files

    - name: Publish transaction
      ansible.builtin.command:
        cmd: "cvmfs_server publish {{ cvmfs_repo }}"
        removes: "/var/spool/cvmfs/{{ cvmfs_repo }}/in_transaction.lock"
      when:
        - create_cvmfs_content_structure_start_transaction
        - create_cvmfs_content_structure_publish_transaction
        - create_cvmfs_content_structure_create_symlinks.changed or create_cvmfs_content_structure_create_files.changed or create_cvmfs_content_structure_create_directories.changed
      register: create_cvmfs_content_structure_publish

    - name: Abort transaction
      ansible.builtin.command:
        cmd: "cvmfs_server abort {{ cvmfs_repo }}"
        removes: "/var/spool/cvmfs/{{ cvmfs_repo }}/in_transaction.lock"
      when: create_cvmfs_content_structure_publish is skipped

  rescue:
    - name: Abort transaction
      ansible.builtin.command:
        cmd: "cvmfs_server abort {{ cvmfs_repo }}"
        removes: "/var/spool/cvmfs/{{ cvmfs_repo }}/in_transaction.lock"
      when:
        - create_cvmfs_content_structure_start_transaction
        - create_cvmfs_content_structure_abort_transaction_on_failures

    - name: Exit because of failure
      ansible.builtin.fail:
        msg: "Task {{ ansible_failed_task }} failed, with result {{ ansible_failed_result }}."
