# Create specified files and symlinks in the CVMFS repository {{ cvmfs_repo }}.
---

- name: "Include the vars file for {{ cvmfs_repo }}"
  ansible.builtin.include_vars: "{{ cvmfs_repo }}.yml"

- name: Start transaction
  ansible.builtin.command: "cvmfs_server transaction {{ cvmfs_repo }}"
  when: create_cvmfs_content_structure_start_transaction

- name: Apply changes to CVMFS repository, if there are any
  block:
  - name: "Create symlinks"
    ansible.builtin.file:
      path: "/cvmfs/{{ cvmfs_repo }}/{{ item }}"
      src: "{{ symlinks[item] }}"
      state: link
      force: true
    with_items: "{{ symlinks }}"
    register: create_symlinks

  - name: "Copy files"
    ansible.builtin.copy:
      src: "{{ item.name }}"
      dest: "/cvmfs/{{ cvmfs_repo }}/{{ item.dest }}"
      mode: "{{ item.mode }}"
    with_items: "{{ files }}"
    register: create_files

  - name: Publish transaction
    ansible.builtin.command: "cvmfs_server publish {{ cvmfs_repo }}"
    when:
      - create_cvmfs_content_structure_start_transaction
      - create_cvmfs_content_structure_publish_transaction
      - create_symlinks.changed or create_files.changed
    register: publish

  - name: Abort transaction
    ansible.builtin.command: "cvmfs_server abort {{ cvmfs_repo }}"
    when: publish is skipped

  rescue:
    - name: Abort transaction
      ansible.builtin.command: "cvmfs_server abort {{ cvmfs_repo }}"
      when:
        - create_cvmfs_content_structure_start_transaction
        - create_cvmfs_content_structure_abort_transaction_on_failures

    - name: Exit because of failure
      ansible.builtin.fail:
        msg: "Task {{ ansible_failed_task }} failed, with result {{ ansible_failed_result }}."
