# Main task which runs do_repo.yml for every CVMFS repo with a vars file.
---

- name: "Find which repositories have a vars file..."
  delegate_to: localhost
  ansible.builtin.stat:
    path: "{{ role_path }}/vars/{{ item.repository }}.yml"
  with_items: "{{ cvmfs_repositories | default(eessi_cvmfs_repositories) }}"
  register: create_cvmfs_content_structure_repo_vars_files

- name: "Apply do_repo for each repository with a vars file"
  ansible.builtin.include_tasks: do_repo.yml
  vars:
    cvmfs_repo: "{{ create_cvmfs_content_structure_repo_vars_file.item.repository }}"
  when: create_cvmfs_content_structure_repo_vars_file.stat.exists
  with_items: "{{ create_cvmfs_content_structure_repo_vars_files.results }}"
  loop_control:
    loop_var: create_cvmfs_content_structure_repo_vars_file
  args:
    apply:
      become: "{{ 'true' if create_cvmfs_content_structure_repo_vars_file.item.owner != lookup('env', 'USER') else 'false' }}"
      become_user: "{{ create_cvmfs_content_structure_repo_vars_file.item.owner }}"
