FROM ubuntu:18.04

USER root

RUN apt-get update
RUN apt-get install -y cron gpg python3.8 python3-pip systemd

RUN python3.8 -m pip install -U pip
RUN python3.8 -m pip install ansible

COPY ./.github/workflows/test-playbook.sh /test-playbook.sh

VOLUME ["/sys/fs/cgroup"]
CMD ["/lib/systemd/systemd"]
