FROM ubuntu:22.04

USER root

RUN apt update
RUN apt install -y cron gpg python3 python3-pip systemd git

RUN python3 -m pip install -U pip
RUN python3 -m pip install ansible

COPY ./.github/workflows/test-playbook.sh /test-playbook.sh

VOLUME ["/sys/fs/cgroup"]
CMD ["/lib/systemd/systemd"]
