FROM ubuntu:20.04

USER root

RUN apt-get update
RUN apt-get install -y cron gpg python3-pip git
RUN env DEBIAN_FRONTEND=noninteractive DEBCONF_NONINTERACTIVE_SEEN=true apt-get install -y systemd

RUN pip3 install ansible

COPY ./.github/workflows/test-playbook.sh /test-playbook.sh

VOLUME ["/sys/fs/cgroup"]
CMD ["/lib/systemd/systemd"]
