name: Test containers

on: [push, pull_request]

# Declare default permissions as read only.
permissions: read-all

jobs:
  test-client-container:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # v3.1.0
      - name: Build the Docker image
        run: docker build . --file containers/Dockerfile.EESSI-client-rocky8
  test-build-container:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # v3.1.0
      - name: Build the Docker image
        run: docker build . --file containers/Dockerfile.EESSI-build-node-debian11
